### ISSUE TITLE
what does the sequences number over 20 mean?

### ISSUE THREAD

**Issue by nuclearslippers** [ZhuYaoHui1998/SWformer-VO#1]
First, Thank you so much for your incredible open-source contribution.
I found that the default sequences in train.py, predict_pose.py, and plot_result.py include sequence numbers above 20, while the KITTI dataset only has sequences numbered 0-20. I modified the train.py and predict_pose.py files according to the dataset and successfully ran them. However, I encountered an issue when reading ".26.txt" in plot_result.py. It is obvious that this file does not exist in my running environment.
Am I missing some steps, or should I change this path?

![Screenshot 2024-11-09 094237](https://github.com/user-attachments/assets/ebbce825-3ac6-4240-9ee3-ebc15ec0b704)

**Comment by ZhuYaoHui1998** [comment]
Are you using your own dataset or KITTI? Because I collected my own dataset to avoid conflicts with the KITTI dataset, I added route 26 with a different numbering. You can replace the 26th line of the 102nd row in the plot result with the path to your dataset's .txt file.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ZhuYaoHui1998/SWformer-VO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月9日(星期六) 上午9:45
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ZhuYaoHui1998/SWformer-VO] what does the sequences number over 20 mean? (Issue #1)





 
First, Thank you so much for your incredible open-source contribution.
 I found that the default sequences in train.py, predict_pose.py, and plot_result.py include sequence numbers above 20, while the KITTI dataset only has sequences numbered 0-20. I modified the train.py and predict_pose.py files according to the dataset and successfully ran them. However, I encountered an issue when reading ".26.txt" in plot_result.py. It is obvious that this file does not exist in my running environment.
 Am I missing some steps, or should I change this path?
 
Screenshot.2024-11-09.094237.png (view on web)

**Comment by nuclearslippers** [comment]
thanks for your reply. I use the KITTI dataset only. So is that mean, I should change the "26.txt" into ".txt" from the KITTI website. or i just directly use the pose without recovering?

**Comment by nuclearslippers** [comment]
well, I made it using the origin data in the .npy. Thanks again.

**Comment by ZhuYaoHui1998** [comment]
> well, I made it using the origin data in the .npy. Thanks again.

no thanks
